(function(g){
'use strict';
const v=g.PanmapApp.panmapV2,s=v.stage90=v.stage90||{},old=v.stage88.compactLayout;
const parameters={growthWeight:.004,neighborWeight:.55,longLabelTangentialBias:9,labelGap:12,iterations:65,neighborRadius:32,focusedParentAnchorWeight:Infinity,contextSpringWeight:1,expansionAreaScale:1.25,animationDuration:380,childGap:9,contextScale:.92};
const mid=old.mid,bounds=v.hierarchicalLabelLayout.bounds,overlap=v.hierarchicalLabelLayout.overlap;
function scaled(n,k){const c=mid(n);return {...n,fontSize:n.fontSize*k,w:n.w*k,h:n.h*k,x:c.x-n.w*k/2,y:c.y-n.h*k/2};}
function energy(nodes,center){const b=bounds([...nodes,center]);return b.w*b.h*parameters.growthWeight+Math.abs(Math.log(b.w/b.h))*85+nodes.reduce((a,n,i)=>{const c=mid(n),r=Math.hypot(c.x,c.y)||1,nearest=Math.min(...nodes.filter((_,j)=>i!==j).map(m=>old.gap(n,m)));return a+r*.32+nearest*parameters.neighborWeight+(n.w>n.h*2?Math.abs(c.x)/r*parameters.longLabelTangentialBias:0);},0);}
function initial(tree){const start=performance.now(),base=old.layout(tree),nodes=base.nodes.map(n=>({...n})),center={...base.center};let e=energy(nodes,center);
for(let k=0;k<parameters.iterations;k++){let moved=0;for(let i=0;i<nodes.length;i++){const n=nodes[i],c=mid(n),r=Math.hypot(c.x,c.y)||1,step=k<30?3:1.5;const candidates=[[-c.x/r,-c.y/r],...Array.from({length:8},(_,j)=>[Math.cos(j*Math.PI/4),Math.sin(j*Math.PI/4)])];let best=n,bestE=e;for(const [dx,dy] of candidates){const p={...n,x:n.x+dx*step,y:n.y+dy*step};if([{x:center.x-14,y:center.y-14,w:center.w+28,h:center.h+28},...nodes.filter((_,j)=>i!==j)].some(o=>overlap(p,o,parameters.labelGap)))continue;const trial=nodes.slice();trial[i]=p;const score=energy(trial,center);if(score<bestE-.001){best=p;bestE=score;}}if(best!==n){nodes[i]=best;e=bestE;moved++;}}if(!moved)break;}
return {nodes,center,bounds:bounds([...nodes,center]),focus:null,durationMs:performance.now()-start};}
function boxTouchesPolygon(b,p,padding=0){const q={x:b.x-padding,y:b.y-padding,w:b.w+2*padding,h:b.h+2*padding};if([[q.x,q.y],[q.x+q.w,q.y],[q.x+q.w,q.y+q.h],[q.x,q.y+q.h]].some(x=>v.labelEnvelope.inside(x,p)))return true;
for(const x of p)if(x[0]>=q.x&&x[0]<=q.x+q.w&&x[1]>=q.y&&x[1]<=q.y+q.h)return true;
for(let i=1;i<p.length;i++){const a=p[i-1],z=p[i],dx=z[0]-a[0],dy=z[1]-a[1];let lo=0,hi=1;for(const [d,t] of [[-dx,a[0]-q.x],[dx,q.x+q.w-a[0]],[-dy,a[1]-q.y],[dy,q.y+q.h-a[1]]]){if(d===0){if(t<0){lo=2;break;}}else if(d<0)lo=Math.max(lo,t/d);else hi=Math.min(hi,t/d);}if(lo<=hi&&lo<=1&&hi>=0)return true;}return false;}
function prepare(tree,base,id){const start=performance.now(),source=base.nodes.find(n=>n.nodeId===id);if(!source)throw Error('请选择一级类别');const parent=scaled(source,1.1),anchor=mid(parent),children=[];
for(const childId of source.children){const label=old.shape(tree.nodes.get(childId));let best=null,bestScore=Infinity;for(let radius=30;radius<=260;radius+=7){for(let a=0;a<32;a++){const angle=a*Math.PI/16,p={...label,x:anchor.x+Math.cos(angle)*radius-label.w/2,y:anchor.y+Math.sin(angle)*radius-label.h/2};if([{x:base.center.x-14,y:base.center.y-14,w:base.center.w+28,h:base.center.h+28},parent,...children].some(n=>overlap(n,p,parameters.childGap)))continue;const b=bounds([parent,...children,p]),near=Math.min(...[parent,...children].map(n=>old.gap(n,p))),score=radius*1.1+b.w*b.h*.003+near*.3+Math.abs(Math.log(b.w/b.h))*20;if(score<bestScore){bestScore=score;best=p;}}if(best&&radius>130)break;}if(!best)throw Error('局部标签预算不足');children.push(best);}
const budget=v.stage88.smoothEnvelope.build([parent,...children],{time:true,preset:'tight',scale:'small'}),extent=bounds(budget.polygon.map(p=>({x:p[0],y:p[1],w:0,h:0})));
return {id,parent,anchor,children,budget,extent,childLabelArea:children.reduce((a,n)=>a+n.w*n.h,0),durationMs:performance.now()-start};}
function deform(base,expansion){const start=performance.now(),direct=base.nodes.filter(n=>n.nodeId!==expansion.id&&old.gap(n,expansion.extent)<parameters.neighborRadius),directIds=new Set(direct.map(n=>n.nodeId)),far=base.nodes.filter(n=>n.nodeId!==expansion.id&&!directIds.has(n.nodeId)),placed=[...far.map(n=>({...n}))];
for(const original of direct.sort((a,b)=>old.gap(b,expansion.extent)-old.gap(a,expansion.extent)||a.nodeId.localeCompare(b.nodeId))){const n=scaled(original,parameters.contextScale),c=mid(n);let best=null,score=Infinity;for(let r=0;r<=270;r+=6){for(let j=0;j<(r?32:1);j++){const a=j*Math.PI/16,p={...n,x:c.x+Math.cos(a)*r-n.w/2,y:c.y+Math.sin(a)*r-n.h/2};if([{x:base.center.x-14,y:base.center.y-14,w:base.center.w+28,h:base.center.h+28},expansion.parent,...expansion.children,...placed].some(o=>overlap(o,p,10))||boxTouchesPolygon(p,expansion.budget.polygon,4))continue;const e=bounds([...placed,p,expansion.parent,...expansion.children]),cost=r*2+e.w*e.h*.0006;if(cost<score){best=p;score=cost;}}if(best&&r>Math.hypot(mid(best).x-c.x,mid(best).y-c.y)+18)break;}if(!best)throw Error('局部邻域让位未收敛');placed.push(best);}
const byId=new Map(placed.map(n=>[n.nodeId,n]));byId.set(expansion.id,expansion.parent);const nodes=[...base.nodes.map(n=>byId.get(n.nodeId)),...expansion.children],moves=base.nodes.filter(n=>n.nodeId!==expansion.id).map(n=>{const a=mid(n),b=mid(byId.get(n.nodeId));return{id:n.nodeId,direct:directIds.has(n.nodeId),distance:Math.hypot(a.x-b.x,a.y-b.y)};});
return {nodes,center:{...base.center},bounds:bounds([...nodes,base.center]),focus:expansion.id,expansion,moves,baseline:base,durationMs:performance.now()-start};}
function collapse(previous){if(!previous.baseline)return previous;return previous.baseline;}
function metrics(model){return {...old.metrics(model),layoutAspectRatio:old.metrics(model).aspectRatio,exactMaxRadialExtent:Math.max(...model.nodes.flatMap(n=>[[n.x,n.y],[n.x+n.w,n.y],[n.x,n.y+n.h],[n.x+n.w,n.y+n.h]].map(p=>Math.hypot(...p))))};}
s.layout={initial,prepare,deform,collapse,metrics,parameters,boxTouchesPolygon,mid,bounds};
})(window);
