(function(g){
'use strict';
const v=g.PanmapApp.panmapV2,s=v.stage88=v.stage88||{};
const parameters={candidateRings:[100,150,200,250],angularSamples:[8,12,16,20],parentAttraction:1,centerAttraction:.32,compactnessWeight:.5,holePenalty:.8,elongationPenalty:60,wrapThreshold:100,gap:28,relaxationIterations:18};
let context;
function measure(text,size){if(!context&&g.document)context=g.document.createElement('canvas').getContext('2d');if(context){context.font=`600 ${size}px "PingFang SC", "Microsoft YaHei", sans-serif`;return context.measureText(text).width;}return [...text].reduce((a,c)=>a+(/[\x00-\x7f]/.test(c)?size*.56:size),0);}
function shape(node){const fontSize=node.categoryLevel===1?18:16,lines=[];let line='';for(const char of node.text){if(line&&measure(line+char,fontSize)>parameters.wrapThreshold){lines.push(line);line='';}line+=char;if(/[、；/]/.test(char)&&measure(line,fontSize)>parameters.wrapThreshold*.65){lines.push(line);line='';}}if(line)lines.push(line);if(lines.length>1&&/(服务|信息)$/.test(node.text)&&measure(node.text.slice(0,-2),fontSize)<=parameters.wrapThreshold){lines.splice(0,lines.length,node.text.slice(0,-2),node.text.slice(-2));}if(lines.length===2&&lines[1].length===1){const all=lines.join(''),split=Math.ceil(all.length/2);lines.splice(0,2,all.slice(0,split),all.slice(split));}return {...node,lines,fontSize,w:Math.max(...lines.map(l=>measure(l,fontSize)))+6,h:lines.length*(fontSize+5)+4};}
const bounds=v.hierarchicalLabelLayout.bounds,overlap=v.hierarchicalLabelLayout.overlap;
const mid=n=>({x:n.x+n.w/2,y:n.y+n.h/2});
const gap=(a,b)=>Math.hypot(Math.max(0,a.x-b.x-b.w,b.x-a.x-a.w),Math.max(0,a.y-b.y-b.h,b.y-a.y-a.h));
function candidate(label,parent,obstacles,preferredAngle){let best=null,score=Infinity;for(let ring=0;ring<14;ring++){const r=label.categoryLevel===2?45+ring*24:(parameters.candidateRings[ring]||250+(ring-3)*35),count=parameters.angularSamples[ring]||24;for(let i=0;i<count;i++)for(const jitter of [0,.12,-.12]){const a=preferredAngle+i*2*Math.PI/count+jitter,p={...label,x:parent.x+Math.cos(a)*r-label.w/2,y:parent.y+Math.sin(a)*r-label.h/2};if(obstacles.some(o=>overlap(p,o,parameters.gap)))continue;const e=bounds([...obstacles,p]),nearest=Math.min(...obstacles.map(o=>gap(p,o))),cost=r*(label.categoryLevel===2?4:1)+(label.categoryLevel===2?(1-Math.cos(a-preferredAngle))*r*2:0)+Math.hypot(p.x+p.w/2,p.y+p.h/2)*parameters.centerAttraction+nearest*parameters.holePenalty+Math.abs(Math.log(e.w/e.h))*parameters.elongationPenalty+Math.max(e.w,e.h)*parameters.compactnessWeight;if(cost<score){score=cost;best=p;}}if(best&&ring>4)break;}if(!best)throw Error('没有无碰撞的候选位置');return best;}
function layout(tree,focus=null){const center={x:-71,y:-43,w:142,h:100},nodes=[];
for(let i=0;i<tree.roots.length;i++){const label=shape(tree.nodes.get(tree.roots[i]));nodes.push(candidate(label,{x:0,y:0},[center,...nodes],-Math.PI/2+i*2.399963));}
// Greedy energy descent: only accept moves that preserve the full multiline bbox clearance.
for(let iteration=0;iteration<parameters.relaxationIterations;iteration++){let movement=0;for(let i=0;i<nodes.length;i++){const n=nodes[i],p=mid(n),norm=Math.hypot(p.x,p.y),step=Math.min(3,norm*.02),trial={...n,x:n.x-p.x/norm*step,y:n.y-p.y/norm*step};if(![center,...nodes.filter((_,j)=>j!==i)].some(o=>overlap(trial,o,parameters.gap))){nodes[i]=trial;movement+=step;}}if(movement<.05)break;}
const baseline=nodes.map(n=>({...n}));let movements=[];
if(focus){const anchor=nodes.find(n=>n.nodeId===focus);if(!anchor)throw Error('只能展开一级类别');const parent=mid(anchor),angle=Math.atan2(parent.y,parent.x);
// Only immediate neighbours make a modest, reversible concession; distant context stays fixed.
for(let i=0;i<nodes.length;i++){const n=nodes[i];if(n===anchor||gap(n,anchor)>70)continue;const p=mid(n),dx=p.x-parent.x,dy=p.y-parent.y,d=Math.hypot(dx,dy)||1,trial={...n,x:n.x+dx/d*18,y:n.y+dy/d*18};if(![center,...nodes.filter((_,j)=>j!==i)].some(o=>overlap(trial,o,parameters.gap)))nodes[i]=trial;}
for(const id of anchor.children){const child=shape(tree.nodes.get(id));nodes.push(candidate(child,parent,[center,...nodes],angle));}
movements=baseline.map(n=>{const q=nodes.find(x=>x.nodeId===n.nodeId);return {id:n.nodeId,distance:Math.hypot(n.x-q.x,n.y-q.y),far:gap(n,anchor)>70};});}
return {nodes,center,bounds:bounds([...nodes,center]),focus,baseline,movement:{maxNeighborMove:Math.max(0,...movements.map(n=>n.distance)),meanNeighborMove:movements.reduce((a,n)=>a+n.distance,0)/(movements.length||1),farNodeMove:Math.max(0,...movements.filter(n=>n.far).map(n=>n.distance))}};}
function metrics(model){const ns=model.nodes,b=bounds(ns),nearest=ns.map((n,i)=>Math.min(...ns.filter((_,j)=>i!==j).map(o=>gap(n,o)))).sort((a,b)=>a-b),quadrants=[0,0,0,0];let overlaps=0;ns.forEach((n,i)=>{const p=mid(n);quadrants[(p.x>=0?0:1)+(p.y>=0?0:2)]++;ns.slice(i+1).forEach(o=>{if(overlap(n,o,0))overlaps++;});});return {labelCount:ns.length,overlapCount:overlaps,meanNearestGap:nearest.reduce((a,b)=>a+b,0)/ns.length,medianNearestGap:nearest[Math.floor(nearest.length/2)],bboxUnionArea:ns.reduce((a,n)=>a+n.w*n.h,0),boundingArea:b.w*b.h,occupiedRatio:ns.reduce((a,n)=>a+n.w*n.h,0)/(b.w*b.h),aspectRatio:Math.max(b.w/b.h,b.h/b.w),maxRadialExtent:Math.max(...ns.map(n=>Math.hypot(Math.abs(n.x)+n.w,Math.abs(n.y)+n.h))),quadrantBalance:quadrants,maxLabelAspectRatio:Math.max(...ns.map(n=>n.w/n.h)),meanLabelAspectRatio:ns.reduce((a,n)=>a+n.w/n.h,0)/ns.length,wrappedLabelCount:ns.filter(n=>n.lines?.length>1).length};}
s.compactLayout={layout,metrics,parameters,shape,mid,gap};
})(window);
