const assert=require('node:assert/strict');const test=require('node:test');const fs=require('node:fs');const vm=require('node:vm');
global.window={PanmapApp:{}};vm.runInThisContext(fs.readFileSync(`${__dirname}/compact-annular-layout.js`,'utf8'));const engine=window.PanmapApp.compactAnnularLayout;
const baseline=JSON.parse(fs.readFileSync(`${__dirname}/../../exports/stage-6-layout/stage20-cache-baseline.json`));const poiById=new Map(baseline.pois.map(poi=>[poi.poiId,poi]));
const input=baseline.accessibility.filter(item=>item.matrixStatus==='ok'&&item.travelTimeSeconds<=1800).map(item=>{const poi=poiById.get(item.poiId);return{poiId:item.poiId,name:poi.name,longitude:poi.location.lon,latitude:poi.location.lat,travelTimeSeconds:item.travelTimeSeconds,ringId:item.matrixBandId};});
const options={center:{longitude:114.296944,latitude:30.546944},compactness:50,fontHierarchy:50,randomSeed:'stage37-fixed-wuhan-20260804'};
test('all three compact algorithms place the identical frozen 252 POIs without geometry violations',()=>{for(const algorithm of ['fermat','poisson-disc','frontier-contact']){const result=engine.layout(input,{...options,algorithm,mode:'geographic'});assert.equal(result.eligible,252);assert.equal(result.placed,252);assert.equal(result.unplaced,0);assert.deepEqual(result.placedByRing,{'ring-0-10':39,'ring-10-20':83,'ring-20-30':130});assert.deepEqual(result.constraints,{overlapCount:0,outsideOwnRingCount:0,centerCollisionCount:0,timeLabelCollisionCount:0});assert.ok(result.nodes.every(node=>node.rotation===0));assert.deepEqual(new Set(result.nodes.map(node=>node.poiId)),new Set(input.map(node=>node.poiId)));}});
test('frontier rings start at the actual inner boundary and end at the configured contour slack',()=>{const result=engine.layout(input,{...options,algorithm:'frontier-contact',mode:'geographic'});for(const ring of result.ringMetrics){assert.ok(ring.unusedInnerBandPx<=4);assert.ok(Math.abs(ring.outerSlackPx-result.tokens.outerContourGapPx)<=.05);}assert.equal(result.ringRadii[1].inner-result.ringRadii[0].outer,result.tokens.interRingGapPx);assert.equal(result.ringRadii[2].inner-result.ringRadii[1].outer,result.tokens.interRingGapPx);assert.ok(result.canvasLogicalWidth<2324);});
test('random-match is stable for a seed and changes only through seeded label-slot matching',()=>{const runs=Array.from({length:5},()=>engine.layout(input,{...options,algorithm:'frontier-contact',mode:'random-match'}));assert.equal(new Set(runs.map(run=>run.layoutFingerprint)).size,1);const alternate=engine.layout(input,{...options,algorithm:'frontier-contact',mode:'random-match',randomSeed:'alternate'});assert.notEqual(alternate.layoutFingerprint,runs[0].layoutFingerprint);assert.equal(runs[0].tokens.coordinateGeneration,'inner-boundary-and-placed-label-contact-frontier');assert.equal(runs[0].tokens.randomContract,'seed changes label-to-constrained-slot matching only');});
test('semantic text and exact-time ring assignments remain frozen',()=>{const result=engine.layout(input,{...options,algorithm:'frontier-contact',mode:'geographic'});const source=new Map(input.map(item=>[item.poiId,item]));for(const node of result.nodes){const frozen=source.get(node.poiId);assert.equal(node.name,frozen.name);assert.equal(node.travelTimeSeconds,frozen.travelTimeSeconds);assert.equal(node.ringId,frozen.ringId);assert.ok(node.fontSize>=12);}assert.equal(result.nodes.filter(node=>node.status!=='placed').length,0);});
