const assert=require('node:assert/strict');const test=require('node:test');const fs=require('node:fs');const vm=require('node:vm');
global.window={PanmapApp:{}};vm.runInThisContext(fs.readFileSync(`${__dirname}/direction-preserving-radial-layout.js`,'utf8'));const engine=window.PanmapApp.directionPreservingRadialLayout;
const center={longitude:114.296944,latitude:30.546944};
function poi(id,longitude,latitude,ringId='ring-0-10',travelTimeSeconds=300,name=id){return{poiId:id,name,longitude,latitude,ringId,travelTimeSeconds};}
test('cardinal and quadrant fixtures preserve every applicable hard half-plane',()=>{const points=[poi('e',center.longitude+.01,center.latitude),poi('w',center.longitude-.01,center.latitude),poi('n',center.longitude,center.latitude+.01),poi('s',center.longitude,center.latitude-.01),poi('ne',center.longitude+.01,center.latitude+.01),poi('nw',center.longitude-.01,center.latitude+.01),poi('se',center.longitude+.01,center.latitude-.01),poi('sw',center.longitude-.01,center.latitude-.01)];const result=engine.layout(points);assert.equal(result.placed,8);assert.equal(result.constraints.eastWestHardViolationCount,0);assert.equal(result.constraints.northSouthHardViolationCount,0);assert.ok(result.nodes.every(node=>node.finalAngularErrorDeg<=30));});
test('objects on a source axis epsilon are exempt only from that axis',()=>{const nearLon=center.longitude+.2/(111320*Math.cos(center.latitude*Math.PI/180));const item=poi('axis',nearLon,center.latitude+.01);const axes=engine.sourceAxes(center,item,1);assert.equal(axes.eastWest,0);assert.equal(axes.northSouth,1);const result=engine.layout([item]);assert.equal(result.constraints.northSouthHardViolationCount,0);assert.ok(result.nodes[0].y<result.center.canvasY);});
test('angle offsets alternate around zero and 0/360 candidates keep shortest direction',()=>{assert.deepEqual(engine.angleOffsets(15,5),[0,5,-5,10,-10,15,-15]);const result=engine.layout([poi('wrap',center.longitude+.01,center.latitude+.0001)]);assert.ok(result.nodes[0].finalAngularErrorDeg<1);});
test('SVG y points down while geographic north is placed above the center',()=>{const result=engine.layout([poi('north',center.longitude,center.latitude+.01)]);assert.ok(result.nodes[0].y<result.center.canvasY);});
test('long label bbox remains exactly within its own annular band',()=>{const result=engine.layout([poi('long',center.longitude+.01,center.latitude+.01,'ring-0-10',300,'这是一个用于精确边界验收的非常长中文标签名称')]);const node=result.nodes[0];const rect={left:node.x-node.width/2,right:node.x+node.width/2,top:node.y-node.height/2,bottom:node.y+node.height/2};const local={left:rect.left-result.center.canvasX,right:rect.right-result.center.canvasX,top:rect.top-result.center.canvasY,bottom:rect.bottom-result.center.canvasY};assert.equal(engine.exactBandAllowed(local,result.ringRadii[0]),true);assert.equal(result.constraints.outsideOwnRingCount,0);});
test('preferred window exhaustion relaxes only inside the legal half-plane',()=>{const crowded=Array.from({length:16},(_,index)=>poi(`crowd-${index}`,center.longitude+.01,center.latitude+.01,'ring-0-10',300,`东北方向长标签${index}号`));const result=engine.layout(crowded,{initialOuterRadiiPx:[170,360,560],maximumExpansionIterations:12});assert.equal(result.placed,crowded.length);assert.ok(result.preferredWindowExceededCount>0);assert.equal(result.constraints.eastWestHardViolationCount,0);assert.equal(result.constraints.northSouthHardViolationCount,0);assert.ok(result.nodes.filter(node=>node.preferredWindowExceeded).every(node=>node.x>result.center.canvasX&&node.y<result.center.canvasY));});
test('insufficient capacity expands rings deterministically and records counts',()=>{const crowded=Array.from({length:20},(_,index)=>poi(`expand-${index}`,center.longitude+.01,center.latitude+.01,'ring-0-10',300,`扩容测试标签${index}`));const a=engine.layout(crowded,{initialOuterRadiiPx:[140,300,480],maximumExpansionIterations:16});const b=engine.layout(crowded,{initialOuterRadiiPx:[140,300,480],maximumExpansionIterations:16});assert.ok(a.expansionIterations>0);assert.equal(a.placed,20);assert.equal(a.layoutFingerprint,b.layoutFingerprint);assert.deepEqual(a.ringExpansionCounts,b.ringExpansionCounts);});
const baseline=JSON.parse(fs.readFileSync(`${__dirname}/../../exports/stage-6-layout/stage20-cache-baseline.json`));const poiById=new Map(baseline.pois.map(p=>[p.poiId,p]));const frozen=baseline.accessibility.filter(a=>a.matrixStatus==='ok'&&a.travelTimeSeconds<=1800).map(a=>{const p=poiById.get(a.poiId);return{poiId:a.poiId,name:p.name,longitude:p.location.lon,latitude:p.location.lat,travelTimeSeconds:a.travelTimeSeconds,ringId:a.matrixBandId};});
test('frozen 252 POIs satisfy every hard gate and five runs are stable without input mutation',()=>{const before=JSON.stringify(frozen);const runs=Array.from({length:5},()=>engine.layout(frozen,{center}));const result=runs[0];assert.equal(new Set(runs.map(run=>run.layoutFingerprint)).size,1);assert.equal(JSON.stringify(frozen),before);assert.equal(result.inputMutationDetected,false);assert.equal(result.placed,252);assert.equal(result.unplaced,0);assert.deepEqual(result.placedByRing,{'ring-0-10':39,'ring-10-20':83,'ring-20-30':130});assert.deepEqual(result.constraints,{overlapCount:0,outsideOwnRingCount:0,centerCollisionCount:0,timeLabelCollisionCount:0,eastWestHardViolationCount:0,northSouthHardViolationCount:0});});
test('layout performs no network access',()=>{const originalFetch=global.fetch;let calls=0;global.fetch=()=>{calls+=1;throw new Error('network forbidden');};try{engine.layout([poi('offline',center.longitude+.01,center.latitude+.01)]);assert.equal(calls,0);}finally{global.fetch=originalFetch;}});
