const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const c={performance,console};c.window=c;vm.createContext(c);for(const p of ['vendor/d3.min.js','taxonomy/category-registry.js','layout/hierarchical-label-layout.js','envelope/label-envelope.js','stage88/compact-layout.js','stage88/smooth-envelope.js','stage90/layout.js','fields/center-exclusion-field.js','fields/shared-semantic-field.js','stage90/scene.js'])vm.runInContext(fs.readFileSync('src/panmap-v2/'+p,'utf8'),c,{filename:p});
const v=c.PanmapApp.panmapV2,s=v.stage90,snapshot=JSON.parse(fs.readFileSync('exports/panmap-v2-gates/snapshot.json')),tree=v.categoryRegistry.build(snapshot),before=v.stage88.compactLayout.layout(tree),base=s.layout.initial(tree);
const area=p=>Math.abs(p.reduce((a,q,i)=>{const r=p[(i+1)%p.length];return a+q[0]*r[1]-r[0]*q[1];},0))/2,perimeter=p=>p.reduce((a,q,i)=>{const r=p[(i+1)%p.length];return a+Math.hypot(q[0]-r[0],q[1]-r[1]);},0),write=(name,value)=>fs.writeFileSync('artifacts/stage90/'+name+'.json',JSON.stringify(value,null,2));
const bm=s.layout.metrics(before),am=s.layout.metrics(base),beforeScene=v.stage88.smoothEnvelope.scene(before),beforeArea=area(beforeScene.time.polygon),beforePerimeter=perimeter(beforeScene.time.polygon);
assert.equal(am.overlapCount,0);assert(am.meanNearestGap<bm.meanNearestGap);assert(am.exactMaxRadialExtent<=bm.exactMaxRadialExtent*1.05);assert.equal(JSON.stringify(base.nodes),JSON.stringify(s.layout.initial(tree).nodes));
write('stage88-baseline-metrics',{...bm,l1Count:16,timeEnvelopeArea:beforeArea,timeEnvelopePerimeter:beforePerimeter,timeEnvelopeCompactness:4*Math.PI*beforeArea/beforePerimeter**2,l1IndependentRegionCount:16,sharedBoundaryLength:0,emptyGapArea:beforeArea-beforeScene.groups.reduce((a,g)=>a+area(g.shape.polygon),0)-before.center.w*before.center.h});
console.log('layout',JSON.stringify({before:bm,after:am}));write('layout-comparison',{before:bm,after:am});
const initial=s.scene.build(tree,base),cases=[{name:'initial',scene:initial}],deformations=[];
for(const text of ['政府机构及社会团体','餐饮服务']){const id=tree.roots.find(id=>tree.nodes.get(id).text===text),scene=s.scene.build(tree,base,id,initial),m=scene.model;
assert.equal(s.layout.metrics(m).overlapCount,0);const a=s.layout.mid(base.nodes.find(n=>n.nodeId===id)),b=s.layout.mid(m.nodes.find(n=>n.nodeId===id));assert(Math.hypot(a.x-b.x,a.y-b.y)<=12);assert.equal(JSON.stringify(m.center),JSON.stringify(base.center));assert.equal(s.layout.collapse(m),base);const direct=m.moves.filter(n=>n.direct),far=m.moves.filter(n=>!n.direct),mean=list=>list.reduce((a,n)=>a+n.distance,0)/(list.length||1);assert.equal(mean(far),0);
const centroid=p=>{let a=0,x=0,y=0;for(let i=0;i<p.length;i++){const q=p[i],r=p[(i+1)%p.length],cross=q[0]*r[1]-r[0]*q[1];a+=cross;x+=(q[0]+r[0])*cross;y+=(q[1]+r[1])*cross;}return{x:x/(3*a),y:y/(3*a)};};const centerBefore=centroid(initial.time.polygon),centerAfter=centroid(scene.time.polygon);deformations.push({units:'SVG user units; browser audit converts to CSS pixels',timeEnvelopeCentroidShiftPx:Math.hypot(centerAfter.x-centerBefore.x,centerAfter.y-centerBefore.y),category:text,focusedParentMovePx:Math.hypot(a.x-b.x,a.y-b.y),directNeighborMeanMovePx:mean(direct),directNeighborMaxMovePx:Math.max(0,...direct.map(n=>n.distance)),farContextMeanMovePx:mean(far),farContextMaxMovePx:Math.max(0,...far.map(n=>n.distance)),directNeighborCount:direct.length,farContextCount:far.length,centerMovePx:0,timeEnvelopeAreaChangeRatio:area(scene.time.polygon)/area(initial.time.polygon)-1,localMaxChildDistance:Math.max(...m.expansion.children.map(n=>Math.hypot(s.layout.mid(n).x-a.x,s.layout.mid(n).y-a.y))),localLayoutDurationMs:m.expansion.durationMs,neighborSolveMs:m.durationMs});cases.push({name:text,scene});}
write('deformation-audit',deformations);write('shared-boundary-audit',cases.map(x=>({state:x.name,...x.scene.field.audit,local:x.scene.local?.audit})));write('l1-visual-weights',initial.field.weights);write('shared-field-parameters',s.sharedSemanticField.parameters);write('local-expansion-parameters',s.layout.parameters);
for(const {name,scene} of cases){console.log(name,scene.field.audit,scene.local?.audit);assert.equal(scene.field.audit.gapArea,0);assert(scene.field.audit.vectorPartitionValid);const centerRegion=scene.field.regions.find(r=>r.id==='center');for(const box of [{x:-25,y:-42,w:50,h:45},{x:-42,y:8,w:84,h:27},{x:-48,y:36,w:96,h:17}])assert(v.labelEnvelope.samples([box],0,8).every(p=>centerRegion.rings.reduce((yes,ring)=>yes!==v.labelEnvelope.inside(p,ring),false)));assert.equal(scene.field.audit.overlapArea,0);assert.equal(scene.field.audit.smallIslandCount,0);assert.equal(scene.field.audit.selfIntersectionCount,0);assert(scene.field.audit.sharedBoundaryPairCount>0);assert(v.labelEnvelope.covers(scene.time.polygon,[...scene.model.nodes,scene.model.center],scene.time.padding));assert(scene.model.nodes.every(n=>{const p=s.layout.mid(n);return scene.field.ownerAt(p.x,p.y)===(n.categoryLevel===1?n.nodeId:n.parentNodeId);}));for(const n of scene.model.nodes){const id=n.categoryLevel===1?n.nodeId:n.parentNodeId,r=scene.field.regions.find(r=>r.id===id);assert(v.labelEnvelope.samples([n],0,8).every(p=>r.rings.reduce((yes,ring)=>yes!==v.labelEnvelope.inside(p,ring),false)));}if(scene.local){assert(scene.local.audit.vectorPartitionValid);assert.equal(scene.local.audit.smallIslandCount,0);assert.equal(scene.local.audit.selfIntersectionCount,0);}}
const replay=s.scene.build(tree,base);assert.equal(JSON.stringify(initial.field.regions),JSON.stringify(replay.field.regions));assert.equal(initial.time.path,s.scene.build(tree,s.layout.collapse(cases[1].scene.model)).time.path);
write('test-results',{passed:true,tests:['No L1/L2 text overlap','Center fixed','Shared owner grid no gap/overlap','Shared regions masked by exact time polygon','No small island','No region self intersection','Deterministic field','Focused anchor stable','Local child budget','Far context fixed','Collapse returns stored baseline','Snapshot reused with zero Provider code'],snapshotSha256:crypto.createHash('sha256').update(fs.readFileSync('exports/panmap-v2-gates/snapshot.json')).digest('hex')});
