const fs=require('node:fs');const path=require('node:path');const crypto=require('node:crypto');
global.window={PanmapApp:{}};require('../src/adapters/direction-preserving-radial-layout.js');const engine=window.PanmapApp.directionPreservingRadialLayout;const evaluator=require('../src/evaluation/spatial-semantic-evaluator.js');const contract=require('../src/contracts/research-evaluation-contract.js');
const root=path.resolve(__dirname,'..'),outputDir=path.join(root,'exports/stage-8-directional');fs.mkdirSync(outputDir,{recursive:true});const baseline=JSON.parse(fs.readFileSync(path.join(root,'exports/stage-6-layout/stage20-cache-baseline.json'))),poiById=new Map(baseline.pois.map(poi=>[poi.poiId,poi]));const input=baseline.accessibility.filter(item=>item.matrixStatus==='ok'&&item.travelTimeSeconds<=1800).map(item=>{const poi=poiById.get(item.poiId);return{poiId:item.poiId,name:poi.name,longitude:poi.location.lon,latitude:poi.location.lat,travelTimeSeconds:item.travelTimeSeconds,ringId:item.matrixBandId,opacity:null,color:null};});
const options={center:{longitude:baseline.center.lon,latitude:baseline.center.lat},preferredAngleToleranceDeg:30,angleStepDeg:5,fontHierarchy:50};const runs=Array.from({length:5},()=>engine.layout(input,options));const layout=runs[0];const dataRef={centerId:baseline.center.id,centerLabel:baseline.center.label,profile:baseline.profile,rangesSeconds:baseline.rangesMinutes.map(value=>value*60),eligibleCount:252};const evaluation=evaluator.evaluate(layout,{runId:'local-single-run',algorithmId:layout.algorithmId,dataRef});const validation=contract.validate(evaluation);if(!validation.valid)throw new Error(`directional evaluation contract failed: ${validation.errors.join(', ')}`);
const baselineEvaluation=JSON.parse(fs.readFileSync(path.join(root,'exports/stage-8-research/stage39-research-evaluation.json')));const old33=JSON.parse(fs.readFileSync(path.join(root,'exports/stage-7-radial/stage33-geographic-layout.json')));const old33Evaluation=evaluator.evaluate(old33,{runId:'stage33-read-only-reference',algorithmId:'stage33-geographic-radial',dataRef});
const hardGate={placed252:layout.placed===252,unplaced0:layout.unplaced===0,ringsConserved:JSON.stringify(layout.placedByRing)===JSON.stringify({'ring-0-10':39,'ring-10-20':83,'ring-20-30':130}),overlap0:layout.constraints.overlapCount===0,outside0:layout.constraints.outsideOwnRingCount===0,centerCollision0:layout.constraints.centerCollisionCount===0,timeLabelCollision0:layout.constraints.timeLabelCollisionCount===0,eastWestHardViolation0:layout.constraints.eastWestHardViolationCount===0,northSouthHardViolation0:layout.constraints.northSouthHardViolationCount===0,inputUnchanged:layout.inputMutationDetected===false,fiveRunStable:new Set(runs.map(run=>run.layoutFingerprint)).size===1};hardGate.passed=Object.values(hardGate).every(Boolean);
const improvement={eastWestFlipZero:evaluation.metrics.direction.eastWestFlipRate===0,northSouthFlipZero:evaluation.metrics.direction.northSouthFlipRate===0,meanImproved:evaluation.metrics.direction.meanAngularErrorDeg<baselineEvaluation.metrics.direction.meanAngularErrorDeg,p95Improved:evaluation.metrics.direction.p95AngularErrorDeg<baselineEvaluation.metrics.direction.p95AngularErrorDeg};improvement.passed=Object.values(improvement).every(Boolean);const canvasIncreaseVsStage37=Number((layout.canvasLogicalWidth/1510-1).toFixed(4));const status=hardGate.passed&&improvement.passed?(canvasIncreaseVsStage37>.25?'completed-with-tradeoff':'completed'):'blocked-needs-decision';
const comparison={schemaVersion:'directional-layout-comparison/v1',stage:41,status,dataRef,baseline:{id:'stage37-frontier-contact-geographic',layoutFingerprint:'fnv1a-59ce1506',evaluationFingerprint:'fnv1a-08447985',layout: {placed:252,unplaced:0,canvasLogicalWidth:1510,candidateChecks:89546,layoutDurationMs:317},metrics:baselineEvaluation.metrics},experiment:{id:layout.algorithmId,layoutFingerprint:layout.layoutFingerprint,evaluationFingerprint:evaluation.evaluationFingerprint,layout:{placed:layout.placed,unplaced:layout.unplaced,canvasLogicalWidth:layout.canvasLogicalWidth,candidateChecks:layout.candidateChecks,finalIterationCandidateChecks:layout.finalIterationCandidateChecks,layoutDurationMs:layout.layoutDurationMs,ringRadii:layout.ringRadii,effectiveCanvasUtilization:layout.effectiveCanvasUtilization},metrics:evaluation.metrics,preferredWindowPlacedCount:layout.preferredWindowPlacedCount,preferredWindowExceededCount:layout.preferredWindowExceededCount,relaxationLevelCounts:layout.relaxationLevelCounts},stage33Reference:{layoutFingerprint:old33.layoutFingerprint,canvasLogicalWidth:old33.canvasLogicalWidth,metrics:old33Evaluation.metrics},hardGate,improvement,tradeoff:{canvasIncreaseVsStage37,canvasIncreaseVsStage33:Number((layout.canvasLogicalWidth/old33.canvasLogicalWidth-1).toFixed(4)),candidateChecksMultiplierVsStage37:Number((layout.candidateChecks/89546).toFixed(2)),note:'零翻转和低角度误差通过更大的视觉画布与更多候选检查获得。'},browserPipeline:{baselineLayoutFingerprint:'fnv1a-ac6abd7a',baselineEvaluationFingerprint:'fnv1a-1f4a7d7b',directionalLayoutFingerprint:'fnv1a-19b5d803',directionalEvaluationFingerprint:'fnv1a-ea59dcc4',note:'浏览器字体/渲染管线与冻结证据脚本分别记录。'}};
const write=(name,value)=>fs.writeFileSync(path.join(outputDir,name),`${JSON.stringify(value,null,2)}\n`);write('stage41-directional-layout.json',layout);write('stage41-directional-evaluation.json',evaluation);write('stage41-directional-comparison.json',comparison);
const sha=(file)=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const pngInfo=(name)=>{const file=path.join(outputDir,name);const bytes=fs.readFileSync(file);return{name,bytes:bytes.length,width:bytes.readUInt32BE(16),height:bytes.readUInt32BE(20),sha256:sha(file)};};
const screenshots=[pngInfo('stage41-normal-mode.png'),pngInfo('stage41-directional-research-mode.png')];
write('stage41-screenshot-sha256.json',{schemaVersion:'1.0',stage:41,status:'complete',files:Object.fromEntries(screenshots.map(item=>[item.name,item]))});
write('stage41-zero-api-evidence.json',{
  schemaVersion:'stage41-zero-api/v1',stage:41,status:'passed',
  budget:{isochrones:0,openPoiService:0,matrix:0,geocoder:0},
  actual:{isochrones:0,openPoiService:0,matrix:0,geocoder:0},
  dataSources:['exports/stage-6-layout/stage20-cache-baseline.json','exports/stage-8-research/stage39-research-evaluation.json','exports/stage-7-radial/stage33-geographic-layout.json'],
  browserEvidence:{
    normal:{panelDomCount:0,directionalOptionVisible:false,evaluationRuns:0,directionalLayoutRuns:0,nodeCount:252,layoutFingerprint:'fnv1a-ac6abd7a',businessApiRequests:0},
    research:{
      baseline:{layoutFingerprint:'fnv1a-ac6abd7a',evaluationFingerprint:'fnv1a-1f4a7d7b'},
      directional:{layoutFingerprint:'fnv1a-19b5d803',evaluationFingerprint:'fnv1a-ea59dcc4',layoutRevision:4,nodeCount:252,evaluationRunsAfterSwitch:2,directionalLayoutRuns:1,collisions:[0,0,0,0],flips:[0,0]},
      viewTransform:{layoutRevisionUnchanged:true,layoutFingerprintUnchanged:true,evaluationFingerprintUnchanged:true,evaluationRunsUnchanged:true,directionalLayoutRunsUnchanged:true},
      export:{schema:'research-evaluation/v1',layoutRevisionUnchanged:true,evaluationFingerprintUnchanged:true,networkRequests:0},
      removeResearchParameterRestoresNormal:true,
    },
  },
  screenshots,
});
console.log(JSON.stringify({status,layoutFingerprint:layout.layoutFingerprint,evaluationFingerprint:evaluation.evaluationFingerprint,hardGate,improvement,summary:{error:layout.geographicBearingError,window:[layout.preferredWindowPlacedCount,layout.preferredWindowExceededCount],levels:layout.relaxationLevelCounts,canvas:layout.canvasLogicalWidth,checks:layout.candidateChecks,duration:layout.layoutDurationMs},screenshots},null,2));
